### ISSUE TITLE
Meta: Package suggestions to be included 

### ISSUE THREAD

**Issue by idnovic** [ublue-os/cosmic#73]
From repo

- [ ] blueman
- [ ] firewall-config
- [ ] nm-connection-editor-desktop
- [ ] system-config-printer
- [ ] seahorse
- [ ] dconf
- [ ] polkit-gnome
- [ ] cups-pk-helper
- [ ] gsettings-desktop-schemas
- [ ] xdg-desktop-portal-gnome

---
From https://copr.fedorainfracloud.org/coprs/wiiznokes/cosmic-applets-unofficial
- [ ] cosmic-ext-applet-clipboard-manager
- [ ] cosmic-ext-applet-external-monitor-brightness
- [ ] cosmic-ext-applet-emoji-selector
- [ ] cosmic-ext-applet-minimon

**Comment by idnovic** [comment]
Optionally to allow a theme to be set cross ui toolkit.
I may have found a few of them in copr repos

- [ ] nwg-look
- [ ] kvantum-qt5
- [ ] kvantum
- [ ] qt5ct
- [ ] qt6ct

**Comment by idnovic** [comment]
Note for Seahorse: A keychain should be added but currently it is not auto unlocked.

**Comment by idnovic** [comment]
I basically added a few GUI apps. Cosmic is very barebones atm.
Some of them offer an applet if we add -applet packages too.
But an extra applet for networking and bluetooth does not make much 
sense because Cosmic already offers a basic applet for these functions.
